VocabModule.addWord('N','fathom','Understand');
VocabModule.addWord('Y','abduct','Kidnap');
VocabModule.addWord('N','redemption','Some thing given or to make up for a past error');
VocabModule.addWord('N','lunatic','An extremely foolish person');
VocabModule.addWord('N','tiramisu','Italian cake flavored with coffee, coco and wine and topped with whipped cream');
VocabModule.addWord('Y','minuscule','Very small');
VocabModule.addWord('N','amble','To walk slowly');
VocabModule.addWord('N','scamper','To go hastily');
VocabModule.addWord('N','impale','To pierce through with any sharp pointed object');
VocabModule.addWord('Y','encroach','To trespass');
VocabModule.addWord('N','fertile','Able to reproduce children');
VocabModule.addWord('Y','limber','Flexible');
VocabModule.addWord('Y','timid','Shy, hesitant, fearful');
VocabModule.addWord('Y','colossal','extremely large');
VocabModule.addWord('N','saturnine','gloomy, humorless');
VocabModule.addWord('N','dour','');
VocabModule.addWord('N','vivacious','(especially of a woman) attractively lively');
VocabModule.addWord('N','jaunty','lively, cheerful');
VocabModule.addWord('N','sprightly','');
VocabModule.addWord('N','impudent','');
VocabModule.addWord('N','insolent','');
VocabModule.addWord('N','timorous','');
VocabModule.addWord('N','diffident','');
VocabModule.addWord('N','chimerical','');
VocabModule.addWord('N','utopia','');
VocabModule.addWord('N','dystopia','');
VocabModule.addWord('N','pragmatic','');
VocabModule.addWord('N','gullible','');
VocabModule.addWord('N','crafty','chaalbaaz');
VocabModule.addWord('N','sensahuma','short for sense of humor');
VocabModule.addWord('N','vagrant','homeless');
VocabModule.addWord('N','domicile','');
VocabModule.addWord('N','succor','assistance');
VocabModule.addWord('N','fowl','any type of bird, the meat of that bird');
VocabModule.addWord('N','runt','undersized.');
VocabModule.addWord('N','bunt','type of baseball shot');
VocabModule.addWord('N','fervor','intense and passionate feeling');
VocabModule.addWord('N','wad','bundle');
VocabModule.addWord('N','wail','to cry out loud');
VocabModule.addWord('N','catamaran','a boat with two parallel hulls');
VocabModule.addWord('N','underdog','predicted loser in a struggle or contest');
VocabModule.addWord('N','parapet','a low wall or railing');
VocabModule.addWord('N','underdog','predicted loser in a struggle or contest');
VocabModule.addWord('N','innate','possessed at birth');
VocabModule.addWord('Y','extirpate','root out and destroy completely');
VocabModule.addWord('Y','unseemly','inappropriate');
VocabModule.addWord('Y','sabbatical','a period of paid leave granted to a college teacher for study or travel, traditionally every seventh year[Sab Baate Kal Karenge because tomorrow is my sabbatical]');
VocabModule.addWord('Y','surly','rude, bad-tempered');
VocabModule.addWord('Y','sagacious','wise');
VocabModule.addWord('Y','facile','effortless');
VocabModule.addWord('Y','mirth','happiness - after child birth there was mirth in family.');
VocabModule.addWord('Y','hegemony','dominance or control');
VocabModule.addWord('Y','shrew','bad-tempered woman');
VocabModule.addWord('Y','abashed','embarrassed');
VocabModule.addWord('Y','quack','a person who dishonestly claims to have special knowledge and skill in some field, typically in medicine');
VocabModule.addWord('Y','sadist','A sadist is someone who obtains pleasure from inflicting pain on others');